name = "portfolio-backend"
compatibility_date = "2024-11-06"
compatibility_flags = [ "nodejs_compat" ]
main = "src/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "a5d9b259-74fd-450d-9af7-750d2e58e593"
migrations_dir = "drizzle"

[observability]
enabled = true

[[routes]]
pattern = "portfolio-api.ntuanvu89.id.vn"
custom_domain = true

[vars]
FRONTEND_URL = "https://ntuanvu89.id.vn"
BETTER_AUTH_SECRET = "your_secret_key"
